spring.application.name=backend

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/kasicircle}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081

# Logging
logging.level.org.springframework.security=DEBUG

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.schema=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG