spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kasicircle
spring.datasource.username=thando_mthethwa
spring.datasource.password=KasiConnect123

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8081

# Logging
logging.level.org.springframework.security=DEBUG